[package]
name = "rustbindings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustbindings"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23.1", features = ["extension-module"] }
numpy = "0.23"
maybenot = { git= "https://github.com/maybenot-io/maybenot.git"}
maybenot-simulator = { git= "https://github.com/maybenot-io/maybenot.git"}
itertools = "0.11"
