[project]
name = "rustbindings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "topiko", email = "topiko1987@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[tool.maturin]
module-name = "src._core"
python-packages = ["src"]
python-source = "src"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
